#!/bin/bash

##############################################
# Set value
##############################################
unset PIPELINE_NAME
unset CROSS_ACCOUNT_PROFILE

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -n|--name)
    PIPELINE_NAME="$2"
    shift # past argument
    shift # past value
    ;;
    -c|--cross-account-profile)
    CROSS_ACCOUNT_PROFILE="$2" # cross account profile
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

##############################################
# Arguments validation
##############################################
if [ -z "$PIPELINE_NAME" ]; then
    echo 'Pipeline name is required.'
    echo 'Usage: create_custom_key_cross_account -n PIPELINE_NAME -c CROSS_ACCOUNT_PROFILE'
    exit 9
fi

if [ -z "$CROSS_ACCOUNT_PROFILE" ]; then
    echo 'Cross account profile is required.'
    echo 'Usage: create_custom_key_cross_account -n PIPELINE_NAME -c CROSS_ACCOUNT_PROFILE'
    exit 9
fi

##############################################
# Parmeters validation
##############################################
ADMIN_ACCOUNT_ARN="$(aws sts get-caller-identity | jq -r '.Arn')"
ADMIN_ACCOUNT_ID="$(echo $ADMIN_ACCOUNT_ARN | cut -d ':' -f 5)"
ADMIN_USER_ID="$(echo $ADMIN_ACCOUNT_ARN | cut -d '/' -f 2)"
CROSS_ACCOUNT_ID="$(aws sts get-caller-identity --profile $CROSS_ACCOUNT_PROFILE | jq -r '.Account')"

if [ -z $ADMIN_ACCOUNT_ID ]; then
    echo The default aws account is not valid.
    exit 9
fi

if [ -z $CROSS_ACCOUNT_ID ]; then
    echo $CROSS_ACCOUNT_PROFILE is not valid profile.
    exit 9
fi

##############################################
# Get informations for Key generation
##############################################
# Get Codepipeline service role ARN
CODEPIPELINE_SERVICE_ROLE_NAME='AWSCodePipelineServiceRole'-"$(aws configure get region)"-$PIPELINE_NAME
CODEPIPELINE_SERVICE_ROLE_ARN="$(aws iam get-role --role-name $CODEPIPELINE_SERVICE_ROLE_NAME 2> /dev/null | jq -r '.Role.Arn')"
if [ -z $CODEPIPELINE_SERVICE_ROLE_ARN ]; then
    echo $CODEPIPELINE_SERVICE_ROLE_NAME is not found. check pipeline service roles.
    exit 9
fi

SERVICE_ROLE_ARNS=",\"$CODEPIPELINE_SERVICE_ROLE_ARN"\"
# Replace SERVICE_ROLE_ARNS
REPLACE_STR='\/'
SERVICE_ROLE_ARNS="${SERVICE_ROLE_ARNS//\//$REPLACE_STR}"

##############################################
# Create customer KMS key
##############################################
KEY_ID="$(aws kms create-key --key-usage 'ENCRYPT_DECRYPT' --origin 'AWS_KMS' --description 'A Key for cross account pipeline' --tags "TagKey=Name,TagValue=$PIPELINE_NAME" "TagKey=TargetAccount,TagValue=$CROSS_ACCOUNT_ID" 2> /dev/null | jq -r '.KeyMetadata.KeyId')"
echo keyId: $KEY_ID
if [ -z $KEY_ID ]; then
    echo Key generation failed.
    exit 9
fi
##############################################
# Create customer KMS key
##############################################
aws kms create-alias \
--alias-name alias/CrossAccountKeyfor-"$PIPELINE_NAME" \
--target-key-id $KEY_ID

##############################################
# Attach policy to customer KMS key 
##############################################
# generate a key policy file
KEY_FILE=kms-key-"$(uuidgen)"
cat policies/KMSKeyConsolePolicyforCrossAccount.json \
    | sed "s/ADMIN-ACCOUNT-ID/$ADMIN_ACCOUNT_ID/g" \
    | sed "s/ADMIN-USER-ID/$ADMIN_USER_ID/g" \
    | sed "s/CROSS-ACCOUNT-ID/$CROSS_ACCOUNT_ID/g" \
    | sed "s/,\"SERVICE-ROLE-ARNS\"/$SERVICE_ROLE_ARNS/g" \
    | sed 's/"/\\"/g' \
    > .config/"$KEY_FILE".json
sed -i -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' .config/"$KEY_FILE".json
cat <<EOF > .config/"$KEY_FILE".json
{
  "Policy": "$(cat .config/"$KEY_FILE".json)"
}
EOF

# put the policy to the KMS key
aws kms put-key-policy \
--key-id $KEY_ID \
--policy-name default \
--cli-input-json file://.config/"$KEY_FILE".json

exit 0