#!/bin/bash
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset REGION
DEFAULT_REGION='ap-northeast-2'

PROFILE_NAME=$1
if [ -z "$PROFILE_NAME" ]; then
    echo 'Profile name is required.'
    exit 1
fi

ACCESS_KEY="$(aws configure get aws_access_key_id --profile $PROFILE_NAME)"
SECRET_KEY="$(aws configure get aws_secret_access_key --profile $PROFILE_NAME)"
if [ -n "$ACCESS_KEY" ] && [ -n "$SECRET_KEY" ]; then
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    exit 0
else
    echo 'AWS Credentials are not set yet'
fi

# set AWS_ACCESS_KEY_ID
while :
do
    echo 'Please enter a AWS_ACCESS_KEY_ID.'
    read LINE
    AWS_ACCESS_KEY_ID="$(echo $LINE)"
    if [ -z "$AWS_ACCESS_KEY_ID" ]; then
        echo 'AWS_ACCESS_KEY_ID is required'
    else
        break
    fi
done
unset LINE

# set AWS_SECRET_ACCESS_KEY
while :
do
    echo 'Please enter a AWS_SECRET_ACCESS_KEY.'
    read LINE
    AWS_SECRET_ACCESS_KEY="$(echo $LINE)"
    LINE=''
    if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
        echo 'AWS_SECRET_ACCESS_KEY is required'
    else
        break
    fi
done
unset LINE

# AWS Configure
aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile $PROFILE_NAME
aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile $PROFILE_NAME
aws configure set region "$DEFAULT_REGION" --profile $PROFILE_NAME
aws configure set output json --profile $PROFILE_NAME

# set REGION
echo "Supported regions"
echo "-------------------"
echo "$(aws ec2 describe-regions | jq -r '.Regions | .[].RegionName')"
echo "-------------------"
echo 'Please enter a region.'
read LINE
REGION="$(echo $LINE)"
if [ -z "$REGION" ]; then
    echo "'$DEFAULT_REGION' will be set as default region"
    REGION=$DEFAULT_REGION
else
    if [ -z "$(aws ec2 describe-regions --query 'Regions[].{Region:RegionName}' | jq -c --arg Region "$REGION" '.[] | select(.Region == $Region)')" ]; then
        echo "$REGION" is not supported. "'$DEFAULT_REGION' will be set as default region"
        REGION=$DEFAULT_REGION
    fi
fi

# Set region
aws configure set region "$REGION" --profile $PROFILE_NAME

exit 0