#!/bin/bash
unset GIT_USER_NAME
unset GIT_USER_EMAIL
USER_NAME="$(git config -l | grep user.name | cut -d '=' -f 2)"
USER_EMAIL="$(git config -l | grep user.email | cut -d '=' -f 2)"

if [ -n "$USER_NAME" ] && [ -n "$USER_EMAIL" ]; then
    echo "Are you $USER_NAME? Y or N"
    read LINE
    if [ $LINE == 'Y' ] || [ $LINE == 'y' ]; then
        unset GIT_USER_NAME
        unset GIT_USER_EMAIL
        exit 0
    fi
fi
unset LINE

# set GIT_USER_NAME
while :
do
    echo 'Please enter a your name.'
    read LINE
    GIT_USER_NAME="$(echo $LINE)"
    if [ -z "$GIT_USER_NAME" ]; then
        echo 'Username is required'
    else
        break
    fi
done
unset LINE

# set GIT_USER_EMAIL
while :
do
    echo 'Please enter a your email.'
    read LINE
    GIT_USER_EMAIL="$(echo $LINE)"
    if [ -z "$GIT_USER_NAME" ]; then
        echo 'User email is required'
    else
        break
    fi
done
unset LINE

# git Configure
git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"

# GIT configure for AWS credential
git config --global credential.helper '!aws codecommit credential-helper $@'
git config --global credential.UseHttpPath true

exit 0