#!/bin/bash
GIT="$(git --version 2> /dev/null | awk '{print $1}')"
PYTHON="$(python3 --version 2> /dev/null | awk '{print $1}')"
PIP="$(pip3 --version 2> /dev/null | awk '{print $1}')"
CURL="$(curl --version 2> /dev/null | awk '{print $1}' | cut -d ' ' -f 1 | head -1 )"
AWS_CLI="$(aws --version 2> /dev/null | awk '{print $1}' | cut -d '/' -f 1 )"
JQ="$(jq --version 2> /dev/null | awk '{print $1}' | cut -d '-' -f 1)"

sudo yum update

# git install
if [ "$GIT" != "git" ]; then
    echo 'install git...'
    sudo yum -y install git
fi

# python3 install
if [ "$PYTHON" != "Python" ]; then
    echo 'install python3...'
    sudo yum -y install python3 python3-distutils
fi

# curl install
if [ "$CURL" != "curl" ]; then
    echo 'install curl...'
    sudo yum -y install curl
fi

# pip3 install
if [ "$PIP" != "pip" ]; then
    echo 'install pip3...'
    sudo yum -y install python3-distutils python3-testresources
    curl -O https://bootstrap.pypa.io/get-pip.py
    python3 get-pip.py --user
    eval echo "~$USER"
    source .profile
fi

# AWS CLI instll
if [ "$AWS_CLI" != "aws-cli" ]; then
    echo 'install aws-cli...'
    pip3 install awscli --upgrade --user
fi

# jq install
if [ "$JQ" != "jq" ]; then
    echo 'install aws-cli...'
    sudo yum -y install jq
fi

echo 'centos setup is done'

exit 0