AWSTemplateFormatVersion: "2010-09-09"
Description: Create new pipeline with existing repository and new branch in AWS
Parameters:
  BranchName:
    Description: CodeCommit branch name
    Type: String
    Default: master
  RepositoryName:
    Description: CodeComit repository name
    Type: String
    Default: myrepo
  CodeDeployServiceRole:
    Description: CodeDeploy service role name
    Type: String
  CodePipelineServiceRole:
    Description: CodePipeline service role name
    Type: String
  CodePipelineArtifactStoreBucket:
    Description: S3 bucket name for codepipeline
    Type: String
Resources:
  AppBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join
      - ''
      - - !Ref RepositoryName
        - !Ref BranchName
        - 'Build'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Description: 'Test Build Stack'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        EnvironmentVariables:
          - Name: varName2
            Value: varValue2
            Type: PLAINTEXT
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 10
      Cache:
        Type: S3
        Location: !Join
              - ''
              - - !Ref CodePipelineArtifactStoreBucket
                - '/'
                - 'prefix'
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED
    DependsOn: CodeBuildRole
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildBasePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
                Effect: Allow
                Resource: 
                    - !Join
                      - ''
                      - - 'arn:aws:logs:'
                        - !Ref 'AWS::Region'
                        - ':'
                        - !Ref 'AWS::AccountId'
                        - ':'
                        - 'log-group:/aws/codebuild/'
                        - !Ref RepositoryName
                        - !Ref BranchName
                        - 'Build'
                    - !Join
                      - ''
                      - - 'arn:aws:logs:'
                        - !Ref 'AWS::Region'
                        - ':'
                        - !Ref 'AWS::AccountId'
                        - ':'
                        - 'log-group:/aws/codebuild/'
                        - !Ref RepositoryName
                        - !Ref BranchName
                        - 'Build'
                        - ':'
                        - '*'
              - Action:
                - 's3:PutObject'
                - 's3:GetObject'
                - 's3:GetObjectVersion'
                - 's3:GetBucketAcl'
                - 's3:GetBucketLocation'
                Effect: Allow
                Resource: !Join
                      - ''
                      - - 'arn:aws:s3:::codepipeline-'
                        - !Ref 'AWS::Region'
                        - '-*'
              - Action:
                - 'codebuild:CreateReportGroup'
                - 'codebuild:CreateReport'
                - 'codebuild:UpdateReport'
                - 'codebuild:BatchPutTestCases'
                Effect: Allow
                Resource: !Join
                      - ''
                      - - 'arn:aws:codebuild:'
                        - !Ref 'AWS::Region'
                        - ':'
                        - !Ref 'AWS::AccountId'
                        - ':'
                        - 'report-group/'
                        - !Ref RepositoryName
                        - !Ref BranchName
                        - 'Build-*'
        - PolicyName: CodeBuildCachePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:PutObject'
                - 's3:GetObject'
                - 's3:GetBucketAcl'
                - 's3:GetBucketLocation'
                Effect: Allow
                Resource: 
                    - !Join
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref CodePipelineArtifactStoreBucket
                    - !Join
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref CodePipelineArtifactStoreBucket
                        - '/*'
  AppDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Join
                  - ''
                  - - !Ref RepositoryName
                    - !Ref BranchName
                    - 'App'
      ComputePlatform: Server
  AppDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref AppDeployApplication
      DeploymentGroupName: !Join 
                  - ''
                  - - !Ref AppDeployApplication
                    - 'Group'
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentStyle:
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE
      ServiceRoleArn: !Join
                  - ''
                  - - 'arn:aws:iam:'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':'
                    - 'role'
                    - '/'
                    - !Ref CodeDeployServiceRole
      Ec2TagSet:
        Ec2TagSetList: 
        - Ec2TagGroup:
          - Key: Key1
            Value: key1
            Type: KEY_AND_VALUE
        - Ec2TagGroup:
          - Key: Key2
            Value: key2
            Type: KEY_AND_VALUE
    DependsOn: AppDeployApplication
  AppPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: codecommit-events-pipeline
      RoleArn: !Join
            - ''
            - - 'arn:aws:iam:'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - 'role'
              - '/'
              - 'service-role'
              - '/'
              - !Ref CodePipelineServiceRole
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                BranchName: !Ref BranchName
                RepositoryName: !Ref RepositoryName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                PrimarySource: SourceArtifact
                ProjectName: !Ref AppBuild
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              InputArtifacts:
                - Name: BuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeploy
              Configuration:
                ApplicationName: !Ref AppDeployApplication
                DeploymentGroupName: !Ref AppDeploymentGroup
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStoreBucket
    DependsOn:
      - AppBuild
      - AppDeployApplication
      - AppDeploymentGroup
  AmazonCloudWatchEventRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'codepipeline:StartPipelineExecution'
                Resource: !Join 
                  - ''
                  - - 'arn:aws:codepipeline:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':'
                    - !Ref AppPipeline
    DependsOn: AppPipeline
  AmazonCloudWatchEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: !Join
        - ''
        - - 'codepipeline-'
          - !Ref RepositoryName
          - '-'
          - !Ref BranchName
          - '-'
          - 'rule'
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        Resources:
          - !Join
            - ''
            - - 'arn:aws:codecommit:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref RepositoryName
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref BranchName
      Targets:
        - Arn: !Join 
            - ''
            - - 'arn:aws:codepipeline:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref AppPipeline
          RoleArn: !GetAtt 
            - AmazonCloudWatchEventRole
            - Arn
          Id: codepipeline-AppPipeline
    DependsOn: AmazonCloudWatchEventRule